### ISSUE TITLE
Custom key support

### ISSUE THREAD

**Issue by xgear-public** [baoyongzhang/Treasure#12]
As far as i understand custom key annotation is not supported now. It would be very convenient to have that feature while migrating to treasure library in existing projects. Usually people already created some preferences and it is not convenient to write interface methods names so that they match key names (for example If i have pref key "key_is_first_launch" i have to write getter method signature as "boolean isKey_Is_First_Launch()").
Do you plan to make such feature or i can pull-request it?

**Comment by baoyongzhang** [comment]
I have plans to implement it, of course, you can pull request it.
