### ISSUE TITLE
Treasure.get() return null

### ISSUE THREAD

**Issue by ben-zhong** [baoyongzhang/Treasure#13]
你好，我很喜欢你的这个库。
不过今天尝试使用的时候发现Treasure.get() 总是return null，所以进一步进行get 和set methods的时候就出现NPE。

我的代码非常简单，就如同例子一样

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        final SimplePreferences preferences = Treasure.get(this, SimplePreferences.class);
        preferences.setUsername("Hello Treasure!");
        String username = preferences.getUsername(); // "Hello Treasure!"}

@Preferences
public interface SimplePreferences {

    @Default("Hello Treasure!")
    String getUsername();

    @Commit
    void setUsername(String username);}

不过final SimplePreferences preferences = Treasure.get(this, SimplePreferences.class); 这句一直都是null。
请问你了解可能产生这个问题的原因吗？ 有可能是annotationprocessor的设置问题吗？ 谢谢

**Comment by ben-zhong** [comment]
刚刚再次测试了一遍，发现当出现多个interface文件的时候，Treasure.get 无法返回正确的结果。例如我的application如果除了上面的代码还含有另一个文件

@Preferences
public interface what {
    int getSome();
    void setSome();
}

Treasure.get 就会返回null。 这似乎是一个bug？

**Comment by baoyongzhang** [comment]
build之后去 app/build/generated/source/apt 目录下找 PreferencesFinder.java 文件，类似于
app/build/generated/source/apt/release/com/baoyz/treasure/PreferencesFinder.java，看一下文件里的内容

**Comment by ben-zhong** [comment]
我现在明白发生什么了，PreferencesFinder.java 是直接返回null的，原因是我这里写错了

@Preferences
public interface what {
int getSome();
void setSome();
}

void setSome();.....漏了参数， 所以不符合语法，然后PreferencesFinder就返回null了

然后在我实际的project里面PreferencesFinder也是返回null的，原因在interface里我添加了删除key的method，void removeNumCopies(); 但我自作聪明的删除了@Remove，以为跟get 和set一样不需要annotation。。。所以语法又错了。。。。

没写过annotation，不知道有没有可能添加一些warning，那就更容易明白是“语法”错误 导致PreferencesFinder返回空了

不过还是谢谢啊！终于解决了

**Comment by baoyongzhang** [comment]
好的，我以后会在编译阶段抛出警告。
