### ISSUE TITLE
Suppressed: java.lang.ClassNotFoundException: com.baoyz.treasure.PreferencesFinder

### ISSUE THREAD

**Issue by spysoos** [baoyongzhang/Treasure#3]
总找不到这个类，不知道为什么。但是用你的demo就没事

**Comment by baoyongzhang** [comment]
是这样配置的么
```groovy
compile 'com.baoyz.treasure:treasure:0.5.0'
provided 'com.baoyz.treasure:treasure-compiler:0.5.0'
```

**Comment by spysoos** [comment]
是的

**Comment by spysoos** [comment]
你有联系方式吗？或者我的QQ 55729890

**Comment by spysoos** [comment]
我的android studio 版本是 1.5 另外 配置有

compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
不过我去掉这个 也没有成功
