### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by woodnaonly** [baoyongzhang/Treasure#7]
java.lang.NoClassDefFoundError: com.baoyz.treasure.GsonConverterFactory
at
 com.baoyz.treasure.MainActivity.onCreate(MainActivity.java:13)

**Comment by baoyongzhang** [comment]
GsonConverterFactory 这个 class 在 demo 里面，和 MainActivity 在同一个 package 下面，你检查一下本地的build环境是不是有问题呢，或者有没有其他的 build 错误信息呢
